name: Release

on:
  workflow_dispatch:

jobs:
  create-github-release:
    permissions:
      contents: write
    uses: marcovaccari/qa-workflows/.github/workflows/create-gh-release.yml@main
    with:
      target: main
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
